LeaYeh/minishell

libraries/libft/build/libft.mk
libraries/libft/inc/libft.h
libraries/libft/src/libft/lists/singly_linked/ft_lstpop.c

```
/**
* The ft_lstpop function removes the first node from a singly linked list and
* returns it - like popping a stack.
*
* @param lst   A double pointer to the first node of the list.
*
* @return      The removed node, or NULL if the list was empty.
*/
```

[FEAT]: Add ft_lstpop to libft

---

Makefile
include/defines.h
include/lexer.h
include/minishell.h
include/tests.h
source/frontend/lexer/create_token_list.c
source/frontend/lexer/get_data.c
source/frontend/lexer/get_type.c
source/frontend/lexer/lexer.c
source/frontend/lexer/lexer_utils.c
source/main.c
tests/test_lexer.c

- Fix all apparent bugs and valgrind issues in lexer.
- Add T_ASSIGNMENT_WORD token recognition to lexer.
- Norminette lexer and split into multiple files.
- Create tests directory and move lexer test into it.
- Add 3 defines used in lexer to defines.h.
- Move ft_lexer function prototype from minishell.h to newly created lexer.h.

[FEAT] Feature-complete lexer

---

libraries/libft/src/libft/chars/ft_isspace.c
libraries/libft/src/libft/lists/doubly_linked/ft_lstadd_back_d.c
libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
libraries/libft/src/libft/lists/singly_linked/ft_lstpop.c
libraries/libft/src/libft/lists/singly_linked/ft_lstpop_content.c
libraries/libft/src/libft/memory/ft_free_and_null.c
libraries/libft/src/libft/memory/ft_memcpy.c
libraries/libft/src/libft/memory/ft_memmove.c
libraries/libft/src/libft/put/ft_putnbr_base_fd.c
libraries/libft/src/libft/put/ft_putnchar_fd.c
libraries/libft/src/libft/put/ft_putnstr_fd.c
libraries/libft/src/libft/strings/ft_split_at_index.c
libraries/libft/src/libft/strings/ft_strisdigits.c
libraries/libft/src/libft/strings/ft_strlcat.c
libraries/libft/src/libft/strings/ft_strlcpy.c
libraries/libft/src/libft/strings/ft_strlen.c
libraries/libft/src/libft/strings/ft_strmatches_any.c
libraries/libft/src/libft/strings/ft_strnstr.c
libraries/libft/src/libft/strings/ft_strtok.c

- By making the documentation comment touch the function definition, the documentation will appear when hovering over the function in VSCode.
- Standardize the formatting.

[DOC] Improve libft documentation for custom functions

---

source/main.c

[FIX] Skip the empty input

---

.github/workflows/test.yml

Also:
- Compare main_test_result with pr_test_result, instead of the other way.
This way lines from main are at the top (or left for side-by-side view).
- Let diff output in side-by-side view.

[CI] Let diff not fail a GH Actions test

---

include/builtins.h
include/utils.h
source/backend/executor/executor_utils.c
source/backend/executor/handle_builtin.c
source/builtins/pwd.c

** need to merge it after #82  and need to rebase again
Actually, getpwd() can be failed but I don't know how to test the error message XDD
I would like to say...ignore it!

[FEAT] Implement builtin function of pwd

---

source/builtins/exit.c
source/builtins/exit_utils.c

The commits are very atomic, so you can pick and choose which ones you'd agree with.

[SUGGESTION] Fix overflow + slight improvements to the exit builtin

---

include/executor.h
include/utils.h
source/backend/executor/handle_builtin.c
source/backend/executor/handle_external.c
source/backend/executor/handle_pipeline.c
source/backend/executor/handle_simple_cmd.c
source/backend/executor/handle_subshell.c
source/backend/redirection/bind.c
source/backend/redirection/pipe_redirect.c
source/backend/redirection/pipe_redirect_utils.c
source/utils/final_cmd_table_utils.c

No big changes.
And again, each commit is atomic, so pick and choose the ones you like.

[SUGGESTIONS] Reduce duplicate code

---

include/defines.h
include/executor.h
include/signals.h
source/backend/executor/executor.c
source/backend/executor/handle_control_op.c
source/backend/executor/handle_external.c
source/backend/executor/handle_pipeline.c
source/backend/executor/handle_simple_cmd.c
source/backend/redirection/heredoc.c
source/init_shell.c
source/main.c
source/signal/signal.c
source/utils/process_utils.c

TODO:
1. After full feature implementation, check newline is well handled
2. Need a support function to check if the final command needs to be skipped

feat: Hook signal handler to SIGINT and SIGQUIT

---

include/defines.h
source/frontend/parser/parser.c

Resolves https://github.com/LeaYeh/minishell/issues/101

[FIX] Set exit code to 2 if syntax error is found

---

include/defines.h
include/expander.h
include/heredoc.h
include/utils.h
source/backend/redirection/heredoc.c
source/backend/redirection/heredoc_utils.c
source/debug/print_expanded_cmd_table.c
source/frontend/expander/bad_substitution.c
source/frontend/expander/expander.c
source/frontend/expander/expander_utils.c
source/frontend/expander/parameter_expansion.c
source/utils/expansion_utils.c
source/utils/final_cmd_table_utils.c

Also align the expander enum names with the other enums with a prefix.

[FEAT] Add heredoc mask to expander to expand even inside single quotes

---

.github/workflows/test.yml
Makefile
libraries/libft/Makefile

- Open a new terminal window with minishell when running `make valfd`.
- Print info about Make version and how it effects the build process.
- Various style improvements to Makefile.

[BUILD] Makefile enhancements + add clang-12 to GH Actions environment

---

source/builtins/echo.c

[FIX] Fix multi `-n` detection for echo

---

.github/scripts/print_all_failed_test_cases.sh
.github/scripts/print_leak_test_cases.sh
.github/workflows/test.yaml
libraries/libft/src/get_next_line/get_next_line.c
source/shell_clean.c

[CI] Improve memory leak tests

---

.github/workflows/test.yaml

Was needed from older change of our GH Actions workflow

[CI] Remove unnecessary checkout step

---

Makefile
include/defines.h
include/signals.h
source/backend/executor/handle_pipeline.c
source/builtins/exit.c
source/init/init_shell.c
source/main.c
source/shell_clean.c
source/signal/signal.c
source/utils/process_utils.c

[FIX] No newline was printed with the exit string when Ctrl+D

---

include/expander.h
source/backend/redirection/heredoc_utils.c
source/frontend/expander/expansion_handler.c
source/frontend/expander/null_expansion.c
source/frontend/expander/word_splitting.c

[FIX] Fix word splitting not removing beginning space

---

include/cd.h
include/defines.h
include/executor.h
source/backend/executor/handle_builtin.c
source/backend/executor/handle_external.c
source/backend/executor/handle_subshell.c
source/backend/redirection/bind.c
source/backend/redirection/io_redirect.c
source/builtins/cd/cd.c
source/builtins/cd/cd_errors.c
source/builtins/cd/cmpnt_list_utils.c
source/builtins/cd/process_path.c
source/builtins/export/export.c
source/builtins/export/print_exported_env.c

[FIX] Fix and standardize exception exit codes

---

.github/workflows/delivery.yaml

Also remove debugging printouts

[CD] Use GITHUB_ENV instead of GITHUB_OUTPUT

---

.github/workflows/delivery.yaml

Also, stderr does not get assign to variables nor redirected to a pipe.

[CD] Fix eval tag creation

---

include/cd.h
include/defines.h
include/expander.h
include/lexer.h
include/utils.h
source/backend/builtins/cd/component_list.c
source/backend/builtins/cd/component_list_utils.c
source/backend/builtins/cd/path.c
source/frontend/expander/bad_substitution.c
source/frontend/expander/expander_task_list.c
source/frontend/expander/expander_task_list_utils.c
source/frontend/expander/expander_utils.c
source/frontend/expander/word_splitting.c
source/frontend/lexer/lexer_utils.c
source/frontend/lexer/token_data_list.c
source/frontend/lexer/token_list.c
source/frontend/lexer/token_type.c
source/utils/symbol_utils.c

* Resolves [STYLE] Change `size_t` to `int` for index #62

[CHORE] Change `size_t` to `int`

---

include/defines.h
include/expander.h
source/backend/executor/executor_utils.c
source/backend/redirection/heredoc_utils.c
source/backend/redirection/io_file.c
source/debug/print_ast_bfs.c
source/debug/print_expanded_cmd_table_content.c
source/frontend/expander/bad_substitution.c
source/frontend/expander/expander.c
source/frontend/expander/expander_task_list.c
source/frontend/expander/null_expansion.c
source/frontend/expander/parameter_expansion.c
source/frontend/expander/quote_removal.c
source/frontend/expander/wildcard_expansion.c
source/frontend/expander/wildcard_file_list.c
source/frontend/expander/wildcard_task_list.c
source/frontend/expander/word_splitting.c
source/frontend/expander/word_splitting_utils.c
source/utils/final_cmd_table_setup.c
todo

Also fix a potential memory leak in `set_file_list()`.

[STYLE] Rename expander variable names

---

.github/actions/setup/action.yaml
.github/actions/summary_test_result/action.yaml
.github/scripts/print_all_failed_test_cases.sh
.github/scripts/print_changed_test_cases.sh
.github/scripts/print_leak_test_cases.sh
.github/scripts/print_test_case.sh
.github/workflows/delivery.yaml
.github/workflows/test.yaml

* Finally helps to explain the inconsistencies of our tester results mentioned in #183.

[CI] Print the outputs of the failed testcases

---

libraries/libft/src/ft_printf/ft_snprintf/sprint_nbr.c
libraries/libft/src/ft_printf/print_nbr.c
libraries/libft/src/libft/put/ft_putnbr_base_fd.c
libraries/libft/src/libft/put/ft_putnbr_fd.c
libraries/libft/src/libft/put/ft_snputnbr_base.c
source/signal/signal_handler.c
source/utils/symbol_utils.c

- 1 out of bounds array access
- 2 operator precedence issues
cppcheck is another static anaylzer.
https://cppcheck.sourceforge.io/

[FIX] Fix issues detected by cppcheck

---

README.md

**Comparison:**
`normal:` 🌊rash
`italic:` <i>🌊</i>rash

[DOC] Make wave emoji italic to make the C in 🌊rash more obvious

---

README.md

Bash stands for "**B**ourne-**A**gain **Sh**ell"
Fish stands for "**F**riendly **I**nteractive **Sh**ell"
Crash stands for "**Cr**eative **A**bort **Sh**ell"

[DOC] Add acronym for Crash to README

---

.github/scripts/print_test_case.sh

- Print test case number in same color as tester.

[CI] Improve readability when the test printouts only follow after a bunch of combined test summaries

---

.github/actions/setup/action.yaml
.github/actions/summary_test_result/action.yaml
.github/scripts/print_all_failed_test_cases.sh
.github/scripts/print_changed_test_cases.sh
.github/scripts/print_leak_test_cases.sh
.github/scripts/print_test_case.sh
.github/workflows/test.yaml

- Use more environment variables that are easily modifiable in one place.
- List all non-default signal handling of the GH Actions envirnoment in the setup action.
- Replaces #357 without the SIGPIPE changes.

[CI] Maintainability improvements

---

README.md

I made the compilation slower.
And at the end I give a small hint by just typing `~` 😉

[DOCS] Add welcome art GIF to README

---

.github/scripts/print_test_case.sh
.github/workflows/regression_test.yaml
.github/workflows/test.yaml

[CI] Adjust CI to new tester updates

---

include/defines.h

Finally the signal source file is without errors! 
https://stackoverflow.com/questions/29201515/what-does-d-default-source-do

[CHORE] Fix red squiggly lines for signal functions

---

Makefile

Sorry, I should have included that in the previous Makefile PR...

[BUILD] Move usage guides to the end of the help messages in Makefile

---

README.md

Light mode -> White background
Dark mode -> Dark background

docs: Make stargazers chart color adaptive
