- source/init_shell.c
In order for ft_strtok to read from the same string, a second call to ft_strtok should be with NULL. Also, the delimiter for the "value" should not be an equal sign [=] but a newline [\n] or, for the very end, a nul-terminator [\0].
> fix: Usage of ft_strtok

- libraries/libft/build/libft.mk
- libraries/libft/inc/libft.h
- libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
The ft_lstinsert_after function inserts a new node after a given node in a singly linked list.
It will be very useful in the lexer.
> feat: Add ft_lstinsert_after to libft

- source/builtins/env.c
- source/init_shell.c
Segfault in ft_strdup can occur when it gets a NULL argument from ft_strtok.
This fix also allows there to be empty **values**.
Also, if any malloc error occurs, env will now exit and not just skip the key-value pair.
Also added "else" to ft_exec_env, just for safety _(and because scan-build complained)_.
> Fix potential segfaults and allow empty key and values in env

- libraries/libft/build/libft.mk
- libraries/libft/inc/libft.h
- libraries/libft/src/libft/strings/ft_split_at_index.c
```
/**
* The ft_split_at_index function splits a string at a given index into two
* parts.
*
* @param str   The string to be split.
* @param index The position at which to split the string.
*
* @return On success, it returns a pointer to an array of two strings:
*         The first string is the part before the index, and the second string
*         is the part from the index to the end of the original string.
*         If the input string is NULL, the index is out of bounds, or memory
*         allocation fails, it returns NULL.
*/
```
> [FEAT]: Add ft_split_at_index to libft

- libraries/libft/build/libft.mk
- libraries/libft/inc/libft.h
- libraries/libft/src/libft/lists/singly_linked/ft_lstpop_content.c
```
/**
* The ft_lstpop_content function removes and frees the first node from a singly
* linked list and returns its content - like popping a stack.
*
* @param lst   A double pointer to the first node of the list.
*
* @return      The content of the removed node, or NULL if the list was empty.
*/
```
> [FEAT] Add ft_lstpop_content to libft

- .github/workflows/build.yml
This is the first step of CI/CD in our project.
For now, it just runs make before a pull request to the main branch.
I don't know yet if it will prevent a merge in case the project is not compilable. This will have to be tested.
> [CI] Set up GitHub Actions by creating build.yml

- include/lexer.h
- source/frontend/lexer/create_token_list.c
- source/frontend/lexer/finetune_token_list.c
- source/frontend/lexer/get_token_data_list.c
- source/frontend/lexer/lexer.c
- source/frontend/lexer/lexer_utils.c
- source/frontend/lexer/set_token_type.c
Included are the following enhancements to the lexer:
1. Rename variable and function names to make it more clear when they are connected to tokens.
2. Set the token type now after the token_list has been fully created. Previously the lexer always switched back and forth between creating more token_list nodes and assigning the token_type.
3. Fix potential memory leaks from not always clearing the token data if any malloc during the lexer fails.
4. Only include the header files in each source file that are necessary.
resolves #19
resolves #21
> [FIX] Set T_ASSIGNMENT_WORD token types correctly in lexer

- Makefile
Add the following improvements to the Makefile:
1. Massively improve build speed by letting 'make' use more CPU cores.
- Added rule to automatically detect which features of Make can be used depending on which version is installed.
2. Separate build artifact files (\*.o/\*.d) into a separate directory.
3. Add dependency file creation to Makefile.
- Now, whenever something in a header file changes, all source files that include this header file will recompile, even if nothing in the source files themselves changed.
- This works by telling the compiler to separate the compilation process into 3 stages:
i.   Pre-processing:
Creates .d files which keep track of all header file dependencies.
ii.  Compiling:
Compiles the source files into object files.
iii. Linking:
Links the object files into …
> [BUILD] Improve Makefile

- libraries/libft/src/libft/lists/singly_linked/ft_lstinsert_after.c
- source/frontend/lexer/lexer_utils.c
Also remove unnecessary parenthesis in lexer_utils.
> [FIX] Fix potential segfault in ft_lstinsert_after in libft

- .github/workflows/test.yml
- This is easier to read and in line with the order of the diffs.
- This makes it easier to quickly check the FAILED_COUNTs, and then see the exact differences.
- If the result got worse, now both the comparison step and the diff step will show a red X in the Actions tab.
- This is done by letting the job continue even after the comparison of the FAILED_COUNTS exits with error. 
The following diff will then always stop the job.
> [CI] Improve the order of the GH Actions result-comparison steps

- .github/workflows/test.yml
From now on the test results should not get any worse anymore.
And the storage space issue was caused by infinitely long log files bc we didn't have pipe redirection yet.
> [CI] Revert the commits that let the GH Actions not prevent a merge

- include/defines.h
- include/utils.h
- libraries/libft/build/libft.mk
- libraries/libft/inc/libft.h
- libraries/libft/src/libft/lists/singly_linked/ft_lstnew_front.c
- source/backend/executor/executor.c
- source/backend/executor/handle_external.c
- source/backend/executor/handle_pipeline.c
- source/init_shell.c
- source/shell_clean.c
- source/utils/process_utils.c
> [FIX] Wait for all children in pipeline to finish before exiting

- .github/workflows/test.yml
- Makefile
Now not the main branch gets checked out for the comparison, but the target branch of the pull request.
In order to accomodate this more clearly, the variable and job names were edited to SOURCE  and TARGET of the pull request.
> [CI] Trigger GH Action for every pull request to any branch and print the commands that caused changes in the tester

- source/builtins/echo.c
* printf without newline will not flash the buffer in time but ft_printf is not thread safe
* Resolves #125
> [FIX] Combine echo args into one string

- Makefile
- include/utils.h
- source/backend/executor/executor.c
- source/backend/executor/handle_builtin.c
- source/backend/executor/handle_simple_cmd.c
- source/shell_clean.c
- source/utils/final_cmd_table_utils.c
The preferred solution will be that the `final_cmd_table` only ever gets created once per `cmd_table`.
For now, the hotfix just says that `setup_fd()` should only be called in `exec_simple_cmd()` , not in `handle_cmd_execution()`.
* Also resolves #138
> [FIX] Hotfix pipe redirection bug

- include/defines.h
- source/main.c
In such a case, init it to `0`, and check before initializing the shell if `PARSING_TABLE` is not `0`.
> [FIX] Protect if PARSING_TABLE macro is not defined

- include/cd.h
- source/backend/executor/executor_utils.c
- source/builtins/cd/environment_utils.c
- source/builtins/cd/get_target_dir.c
If `PATH` is `NULL` or doesn't exist, try to find the executable in the current directory.
Also:
* Change `extract_env()` to `get_value_with_key()` and remove unnecessary malloc from it.
Also fix differentiation between, for example, `AA` and `AAA` env variables by checking if a '=' is after the key.
> [FIX] Handle non-existing PATH env variable for getting the exec path

- include/builtins.h
- include/defines.h
- include/export.h
- source/backend/executor/handle_builtin.c
- source/builtins/export/export.c
- source/builtins/export/print_exported_env.c
---
- If no arguments, print all exported environment variables ordered by ASCII value, with `export ` prepended.
- If the variable has a value, an `=` gets printed after the variable name and the value gets put in double-quotes.
**Example:** 
```sh
bash-5.1$ export VAR='"'
bash-5.1$ export
export VAR="\""
```
How should we handle this?
This is how it looks for us atm:
```sh
export VAR="""
```
> [FEAT] Implement export without arguments -> print out the exported environment

- .gitignore
- include/export.h
- include/init.h
- include/utils.h
- source/builtins/export/export.c
- source/frontend/expander/bad_substitution.c
- source/frontend/expander/expand_variable.c
- source/frontend/expander/expander_utils.c
- source/frontend/lexer/set_token_type.c
- source/init/setup_env_list.c
- source/utils/env_list_utils.c
- source/utils/env_utils.c
- source/utils/string_utils.c
- todo
---
- If one of the variable assignments is not a valid variable name, the return value will be GENERAL_ERROR (1), but export will still go through all arguments.
The error message gets printed for every invalid identifier.
- If the key does not already exist, a new env_node with the key will be created and ...
- if the argument string does not have an '=', the value will be set to NULL.
- else, the value will be extracted from the argument string.
- If the key already exists and ...
- if the argument string does have an '=', the value of the matching key will be replaced.
- In either case the env_node will be set to be exported.
> [FEAT] Implement full export with arguments

- Makefile
- include/builtins.h
- source/backend/executor/handle_builtin.c
- source/builtins/unset.c
---
- The function `remove_env_node()` was already implemented in this commit  [16731fa](https://github.com/LeaYeh/minishell/commit/16731fab3a64c38921f89b4fbb0a6382229a57d7#diff-34af145bb7235c58767c147eb40e76a9ad0cba08a045af75a9137ca4bc10e5cc) when implementing cd.
- Also add `noenv` goal to Makefile.
It starts minishell with no environment (and with valgrind).
> [FEAT] Implement unset

- include/defines.h
- include/lexer.h
- source/frontend/lexer/create_token_list.c
- source/frontend/lexer/lexer_utils.c
* ~~First solve #179~~
---
Test case:
```sh
echo &foo
```
Previously (wrong):
```sh
& foo
```
Fixed:
```sh
&foo
```
> [FIX] Fix wrong token recognition of single `&`

- source/builtins/exit_utils.c
Should be `exit: : numeric argument required`.
Also remove the commented out part, as exit is correct now.
> [FIX] Fix `exit ""`

- libraries/libft/src/get_next_line/get_next_line.c
- source/shell_clean.c
Remove the ability to read from multiple fds at the same time to be able to free the buffer if invalid input to `get_next_line()` is given.
> [FIX] Free the static buffer in `get_next_line()`

- .github/workflows/test.yaml
* Reverts LeaYeh/minishell#198
It didn't change the results in the other tests and the '42_minishell_tester' directory still shows up in the GH Actions environment.
With the checkout step before the summarize step it will be easier to update the summarize step and immediatly see the changes.
> Revert "[CI] Remove unnecessary checkout step"

- .github/actions/setup/action.yaml
- Makefile
- source/backend/executor/handle_external.c
- source/backend/executor/handle_simple_cmd.c
If SIGPIPE would not get catched or ignored, the default behavior is to terminate the process. This would cause memory leaks for us, as in the example `echo 1 | >tmp_out`.
* Resolves [LEAK] `echo 1 | >tmp_out` leaks #179
> [FIX] Fix memory leaks when SIGPIPE occured in minishell child process

- source/shell_clean.c
When the process terminates, the operating system will reclaim all the memory allocated by the program, including the memory used by readline's history entries. So, from a memory leak perspective within the context of the program's lifetime, not calling rl_clear_history() before exiting won't cause a leak.
> [FIX] Clean readline history when exiting shell

- include/executor.h
- include/utils.h
- source/backend/executor/handle_builtin.c
- source/backend/executor/handle_external.c
- source/backend/executor/handle_subshell.c
- source/backend/redirection/bind.c
- source/backend/redirection/io_redirect.c
- source/frontend/parser/cmd_table_symbol.c
- source/utils/cmd_table_status_utils.c
In the parser, instead of filling every simple cmd table  with a redirect from outside of a subshell, fill the subshell start cmd table.
In the executor, the redirection gets then inherited to all child processes of the subshell.
* Resolves #72
> [FIX] Fix order of redirections for subshells

- source/main.c
* I made a new branch and PR bc the branch from #209 has a typo.
---
When the terminal window gets resized, `SIGWINCH` gets sent to the `readline()` function which then sets `errno` to `EINTR`. However, `readline()` still returns the string it read as usual.
All other `errno` checks are necessary to protect against `malloc()` and `read()` failures. 
I tested and can confirm that `read()` does not listen to `SIGWINCH` and therefore also doesn't set `errno` to `EINTR` in such a case.
* Resolves #200
> [FIX] Fix unresponsiveness after terminal window resizing

- .github/workflows/test.yaml
- source/backend/executor/handle_builtin.c
- source/backend/executor/handle_simple_cmd.c
- source/frontend/parser/cmd_table_symbol.c
- source/utils/cmd_table_operation_utils.c
- source/utils/cmd_table_status_utils.c
- **Set C_SIMPLE_CMD as the default cmd_table type.**
This make more sense bc f.e. `> outfile` should still get a command table and get to the executor.
And in the executor, we expect at least a C_SIMPLE_CMD in order to do anything with it.
- **The return statements are a bit misleading.**
They are an artifact from before the error handling functions via signals were changed.
`SIGTERM` only doesn't exit in subshell level 0.
Therefore, in any functions that are accessable from the main process, a continuation after raise_error has to be considered.
`exec_simple_cmd()` is not accessable from the main process.
And in `handle_builtin()`, there is an explicit check that this is not in subshell level 0.
- **Improve compilation tests in GH Actions.**
When just running cc, the default is gcc. …
> [STYLE] Change default cmd_table type and remove dead return statements

- include/defines.h
- include/signals.h
- source/backend/executor/executor.c
- source/backend/executor/handle_control_op.c
- source/backend/executor/handle_pipeline.c
- source/init/init_shell.c
- source/shell_clean.c
- source/signal/signal.c
Test case:
```sh
cat | ls && echo 123
```
~~Working behavior, but wrong exit code:~~ **SOLVED**
```sh
(cat | ls) && echo 123
```
---
```sh
echo 123 && cat | ls
```
---
```sh
(cat | ls) && echo 123
```
> [FIX] Stop full cmd list if received `Ctrl+C`

- include/defines.h
- include/executor.h
- include/expander.h
- include/heredoc.h
- include/utils.h
- source/backend/executor/handle_builtin.c
- source/backend/executor/handle_external.c
- source/backend/executor/handle_subshell.c
- source/backend/redirection/bind.c
- source/backend/redirection/heredoc.c
- source/backend/redirection/heredoc_utils.c
- source/backend/redirection/io_redirect.c
- source/debug/print_cmd_table.c
- source/debug/print_expanded_cmd_table.c
- source/frontend/expander/bad_substitution.c
- source/frontend/expander/expander.c
- source/frontend/expander/expander_task_list.c
- source/frontend/expander/expansion_handler.c
- source/frontend/parser/cmd_table_symbol.c
- source/utils/expansion_utils.c
- source/utils/final_cmd_table_setup_utils.c
- source/utils/io_redirect_utils.c
- source/utils/string_utils.c
not working...
```sh
bash-5.1$ export A="     "
bash-5.1$ echo 1 > abc > $A > def
```
> [FIX] Expand target filename when handle io redirection

- include/defines.h
In commit ca5310f it was necessary to put a `\n` at the beginning of the `ERROR_HEREDOC_UNEXPECTED_EOF` message. This was bc the error message appeared in the same line as the heredoc prompt.
This is not the case any more.
---
* Resolves [BUG] Ctrl+D in heredoc prints one too much line #215
> [FIX] Fix Ctrl+D in heredoc printing one too much line

- source/builtins/exit_utils.c
The following cases should all be considered as valid arguments for exit:
```
exit "         5"
```
```
exit "         5                                                                      "
```
The following should **not** be considered a valid arguments for exit:
```
exit +
```
```
exit -
```
Christian was so kind to let us know of this issue. He noticed it when looking through our code on his own, and he didn't even need to test it to see the issue.
> [FIX] Fix exit builtin with whitespace in arguments

- source/backend/executor/executor.c
- source/backend/executor/handle_builtin.c
I tested bash with `ulimit -u`.
External commands failed to fork, but an input like `> outfile` still created the outfile. This means, with no simple command, bash creates the files in its own process. For a commands like `ls > outfile2`, the file was not created with ulimit -u active.
> [FIX] Fix IO files being created in child process when no scmd

- source/builtins/exit.c
- source/builtins/exit_utils.c
Test cases:
```sh
exit 1111111111111111111111111111111111
```
```sh
exit 9999999999999999999999999999999999
```
```sh
exit "     9223372036854775807                                      "
```
> [FIX] Fix exit codes from exit builtin

- source/backend/builtins/exit/exit.c
- source/backend/builtins/exit/exit_utils.c
- source/main.c
- Also call the exit builtin when receiving EOF - bash does it the same way.
I tested it in bash like this and the `exit` message gets output to the file:
```sh
bash-5.1$ exit 2>/file
```
I also looked at the source code of bash and found the following lines that confirm that the exit builtin prints to stderr:
```c
int
exit_builtin (list)
WORD_LIST *list;
{
CHECK_HELPOPT (list);
if (interactive)
{
fprintf (stderr, login_shell ? _("logout\n") : "exit\n");
fflush (stderr);
}
return (exit_or_logout (list));
}
```
https://github.com/bminor/bash/blob/f3b6bd19457e260b65d11f2712ec3da56cef463f/builtins/exit.def#L64
And when receiving EOF via Ctrl+D bash just calls the exit builtin:
```c
/* If we have EOF as the only input unit, this user wants to leave
the shell.  If the shell is not interactive, …
```
> [FIX] Print exit msg to stderr

- include/defines.h
- source/backend/executor/executor.c
- source/shell_struct/init.c
- source/signal/signal_handler.c
The heredoc signal handler does exactly the same thing as the standard signal handler for `SIGINT`.
And it makes sense that the behavior of `SIGINT` should be the same.
> [REFACTOR] Merge `SIGINT` handling of heredoc with standard

- Makefile
It forcefully cleans up the _obj and _dep directories in the build directory. 
When source filenames change, the build artifacts with the old filenames do not get deleted by fclean. 
This is for safety reasons so that only files known to the Makefile get deleted, and no files that might have gotten into these directories by accident.
> [BUILD] Add `ffclean` goal to Makefile

- source/frontend/expander/expander_task_list_utils.c
- source/frontend/lexer/lexer_utils.c
- source/frontend/lexer/token_list.c
- source/frontend/parser/parser_data.c
- source/utils/cmd_table_operation_utils.c
- source/utils/io_redirect_utils.c
The following cases were tested with funcheck:
```bash
echo123
echo 123
ls
```
```bash
(echo 123) | cat
```
```bash
echo < Makefile > out | (hi || ls) > out2 && this
```
```bash
echo<Makefile>out|(hi||ls)>out2&&"$USER"&&"||||"|'|'
```
```bash
"'${}'" | ${"{
```
```bash
"'${}'" | ${""}
```
> [FIX] Fix funcheck without `-a` option

- source/backend/redirection/heredoc.c
Since now there are also redirect lists in cmd_tables of type other than C_SIMPLE_CMD, they should not be skipped anymore when checking for heredoc io_redirect nodes.
* Resolves #274
> [FIX] Fix heredoc for subshell redirect

- source/shell_struct/clean.c
- source/utils/cmd_table_operation_utils.c
- source/utils/io_redirect_utils.c
- source/utils/token_utils.c
All the calls to `ft_free_and_null()` would just set the local pointer of the freeing function to NULL. 
This might give a false sense of safety that the pointer that gets put as an argument also gets set to NULL.
* These changes were made in #202.
This new PR only changes those `ft_free_and_null()`s back to `free()` that make no difference to signal interrupt behavior.
> [CHORE] Avoid misleading `ft_free_and_null()`s

- .github/actions/cleanup/action.yaml
- .github/actions/norminette/action.yaml
- .github/actions/setup/action.yaml
- .github/actions/summary_test_result/action.yaml
- .github/workflows/delivery.yaml
- .github/workflows/norminette.yaml
- .github/workflows/test.yaml
The branch to run the workflow on can be chosen with a drop-down menu, I think.
It's a useful option in order to not have to delete all the files locally and to quickly check norminette at any time.
> [CI] Add manually triggered norminette workflow

- Makefile
- build/source_files.mk
- include/defines.h
- include/expander.h
- include/heredoc.h
- include/utils.h
- source/backend/redirection/heredoc.c
- source/backend/redirection/heredoc_utils.c
- source/frontend/expander/expander.c
- source/frontend/expander/expander_task_list.c
- source/frontend/expander/expander_task_list_utils.c
- source/frontend/expander/expander_utils.c
- source/frontend/expander/null_expansion.c
- source/frontend/expander/quote_removal.c
- source/frontend/expander/special_param_expansion.c
- source/frontend/expander/variable_expansion.c
- source/frontend/expander/word_splitting.c
- source/frontend/expander/word_splitting_utils.c
- source/utils/string_utils.c
- todo
---
The issue was caused by too early quote removal.
Now the quotes get removed at the end of the expansion process, as is specified in the GNU Bash manual as well.
- All expander tasks now have a double pointer to the string saved in the corresponding `lst` node.
- Every entry to the expander now gets put into a `lst` node immediately.
---
* Resolves #281
> [FIX] Fix wrong null-expansion after word-splitting and quote combination

- .github/workflows/test.yaml
- Makefile
- include/defines.h
- source/backend/builtins/exit/exit.c
- source/backend/redirection/io_file.c
- source/shell_struct/init.c
- When expanding words after redirection operators, call expander with different flags depending on the interactive mode.
- This allows to replace the test mode macro and compilation with `shell->is_interactive` variable.
* Resolves #296
> [FIX] Fix filename expansion in non-interactive mode

- Makefile
This is also useful for GH Actions to see which exact version is compiling.
> [BUILD] Print version of compiler when compiling

- include/defines.h
- source/frontend/parser/parsing_table_operation.c
---
- The macro was one too less than the actual amount of rows of the parsing table.
This got apparent when placing the `PT_ROW_NUM` macro into the parsing table array declarations. The compiler complained that there were excess elements in array initializer.
- Also rename the PT_ macros bc `COL_SIZE` would mean lenght of the column, but it actually stands for the amount of columns.
Same for the rows.
> [FIX] Fix `PT_ROWS` size

- Makefile
- It is now not dependent on the Make version anymore, it can always compile everything, including libft, in parallel.
- It uses a recursive call to Make to make sure libft is fully compiled before compiling minishell.
- It still checks which Make version is installed, and uses the `.WAIT` feature, if possible.
It is better for performance and generally recommended to not use recursive calls to Make.
> [BUILD] Change Makefile to always compile in parallel

- include/lexer.h
- include/parser.h
- include/utils.h
- source/frontend/lexer/lexer_utils.c
- source/frontend/lexer/token_list.c
- source/frontend/lexer/token_type.c
- source/frontend/parser/parser.c
- source/frontend/parser/parser_action.c
- source/frontend/parser/parser_data.c
- source/shell/clean.c
- source/utils/token_utils.c
---
`node` should be a `t_list`, just `token` a `t_tok`.
* Resolves #52
> [STYLE] Rename `token_node` to `token` when not a `t_list`

- libraries/libft/src/libft/chars/ft_isalpha.c
- libraries/libft/src/libft/chars/ft_tolower.c
- libraries/libft/src/libft/chars/ft_toupper.c
It might have an impact for wildcard expansion inside of a directory with a huge amount of files.
In wildcard expansion, `ft_isalpha()`, `ft_tolower()` and `ft_toupper()` are used a lot in merge sort.
> [LIB] Use bitwise operators in basic alphabet functions to improve performance

- Makefile
- libraries/libft/Makefile
The libft Makefile will now inherit many of the Makefile variables from the minishell Makefile.
This makes libft compile in the exact same way as minishell does.
For example, if you'd like to compile with -O3 or without -g, it will also apply to libft.
> [BUILD] Makefile improvements

- libraries/libft/src/libft/chars/ft_isalpha.c
- libraries/libft/src/libft/chars/ft_tolower.c
- libraries/libft/src/libft/chars/ft_toupper.c
The bitwise operations messed up non-alphabetic characters.
To fix this, adding a `ft_isalpha()` check in front defeats the performance reason to use bitwise operators.
> [REVERT] Revert PR #323

- build/source_files.mk
- include/defines.h
- include/utils.h
- libraries/libft/build/libft.mk
- libraries/libft/inc/ft_printf.h
- libraries/libft/src/ft_printf/ft_snprintf/check_args.c
- libraries/libft/src/ft_printf/ft_snprintf/ft_vsnprintf.c
- source/backend/builtins/cd/cd_errors.c
- source/backend/builtins/cd/cd_utils.c
- source/backend/builtins/exit/exit.c
- source/backend/builtins/export/export.c
- source/backend/builtins/pwd.c
- source/backend/executor/external_cmd.c
- source/backend/executor/wait_process.c
- source/backend/redirection/heredoc.c
- source/backend/redirection/io_file.c
- source/backend/redirection/pipe_utils.c
- source/backend/redirection/stdio_bind.c
- source/frontend/expander/bad_substitution.c
- source/frontend/lexer/lexer_utils.c
- source/frontend/parser/syntax_error.c
- source/utils/error_utils.c
- source/utils/file_utils.c
If multiple processes print to stderr at the same time, with `ft_dprintf()`, multiple calls to `write()` might be called.
This can cause the error messages to be interleaved.
The solution is to first use `ft_vsnprintf()` to convert the format string with all its arguments into a buffer string, and then print that string at once with one call to `write()`.
The buffer string for the error message is set to 131072 bytes.
If an error message is longer, it would get truncated.
---
A va_list may be passed as an argument to
another function; if that function invokes the va_arg macro, the
value of the va_list in the calling function is indeterminate and shall be passed to the va_end
macro prior to any further reference.
It is permitted to create a pointer to a va_list and pass that pointer to …
> [FIX] Fix interleaved error messages

- source/utils/file_utils.c
Just check if the file exists before trying to remove it.
Otherwise it would print:
```
crash: warning: failed to remove file `/tmp/crash_hd_2526708-2'
```
> [FIX] Fix file removal error when Ctrl+C in heredoc

- libraries/libft/build/libft.mk
- libraries/libft/inc/libft.h
- libraries/libft/src/chars/ft_issign.c
- libraries/libft/src/numbers/ft_isoverflow_int.c
- libraries/libft/src/numbers/ft_isoverflow_long.c
- source/backend/builtins/exit/exit_utils.c
The overflow check was wrong in a case like `exit 93`. It reported `numeric argument required`.
This was because the overflow check did `ft_strncmp()` even if the length of the number_string is less than the long_max string.
As for putting the functions into libft, I think it's good to put them into libft bc I also need them for philosophers and we will also be able to use them for miniRT.
> [FIX] Fix overflow check for exit builtin and add overflow-check functions to libft

- source/backend/builtins/cd/cd.c
It also makes sense to print the new directory before any potential errors from updating the PWD environment variables, because the current working directory has already been switched.
* Resolves #336.
> [FIX] Fix `cd -` with `OLDPWD=""` not printing an empty line

- README.md
- include/signals.h
- source/backend/executor/external_cmd.c
- source/shell/init.c
- source/signal/exception_broadcaster.c
- source/signal/signal_handler.c
While `SIGABRT` defaults to termination, it is also expected to produce a core dump. If we don't do that, we would change the expected behavior of `SIGABRT`.
An example usage that produces a `SIGABRT` signal is the `abort()` function.
Note: The `abort()` function would usually still work as expected (from the `abort()` manual):
> If the SIGABRT signal is ignored, or caught by a handler that returns, the abort() function will still terminate the process.  It does this by restoring the default disposition for SIGABRT and then raising the signal for a second time.
However, in our case our signal handler for `SIGABRT` does not return but exit, hence the abort function never gets the chance to send the signal a second time with default behavior.
---
- Also remove prototype of non-existing …
> [FIX] Fix `SIGABRT` misuse by switching to `SIGUSR1`

- source/backend/builtins/pwd.c
The `CMD_EXEC_FAILED` exit code should only happen if `execve()` failed.
> [FIX] Fix `pwd` exit code

- .github/actions/cleanup_full/action.yaml
- .github/actions/cleanup_partial/action.yaml
I confirmed with Elidjah a while ago that it's allowed in the evaluation. It's allowed bc it's part of git. 
It's also useful during the evaluations to see more clearly what we edited during the eval.
> [CD] Allow .gitignore file and debug folder in evaluation branch

- include/defines.h
On some systems, readline needs the stdio.h header file to be included outside of it.
> [CHORE] Add back stdio.h for compatibility with some systems

- include/defines.h
- include/signals.h
- source/backend/builtins/cd/cd.c
- source/backend/builtins/cd/cd_errors.c
- source/backend/builtins/cd/component_list_utils.c
- source/backend/builtins/cd/path.c
- source/backend/builtins/export/export.c
- source/backend/builtins/export/export_output.c
- source/backend/executor/builtin_cmd.c
- source/backend/executor/external_cmd.c
- source/backend/executor/pipeline_process.c
- source/frontend/lexer/lexer.c
- source/frontend/parser/parser.c
- source/main.c
- source/shell/init.c
- source/signal/exception_broadcaster.c
- source/signal/signal_handler.c
- **Remove unnecessary protection for `sigemptyset()` failure.**
It is not necessary to protect `sigemptyset()` since the only possible failure is when passing `NULL` to it which would set errno to `EINVAL`.
Here is the source code of `sigemptyset()`:
```c
/* Clear all signals from SET.  */
int
sigemptyset (sigset_t *set)
{
if (set == NULL)
{
__set_errno (EINVAL);
return -1;
}
__sigemptyset (set);
return 0;
}
```
- **Replace `PREPROCESS_ERROR` with `MALLOC_ERROR`.**
I tested bash and the exit code when its malloc fails in the parsing is also `2`.
- **Replace `BUILTIN_ERROR` with `MALLOC_ERROR`.**
`BUILTIN_ERROR`s were only used where anywhere outside of builtins `MALLOC_ERROR` would be used.
And the value of `BUILTIN_ERROR` was relatively arbitrary too.
> [CHORE] Error-macro and `setup_signal()` simplification

- README.md
- include/builtins.h
- include/cd.h
- include/defines.h
- include/export.h
- include/utils.h
- source/backend/builtins/cd/cd.c
- source/backend/builtins/cd/env_pwd_update.c
- source/backend/builtins/echo.c
- source/backend/builtins/export/export.c
- source/backend/builtins/export/export_output.c
- source/backend/builtins/pwd.c
- source/backend/executor/builtin_cmd.c
- source/backend/executor/external_cmd.c
- source/shell/clean.c
- source/shell/default_env_list.c
- source/shell/init.c
- source/signal/signal_handler.c
- source/utils/env_list_operation_utils.c
By setting up a signal handler that cleans and exits for SIGPIPE, we exit with the first `write()` to a broken pipe without trying over and over again.
To avoid memory leaks, allocations in builtins that have not been freed before a call to `write()` have to be safed into the `shell` struct so that they can be freed in the signal handler.
---
Also:
- Use `ft_bzero()` to init shell struct to 0.
- Shorten abort message.
- Make environment list operation functions more memory save.
- Fix `sa.sa_flags` not matching with the function pointers.
> [REFACTOR] Exit for SIGPIPE signal without leaks

- source/backend/builtins/cd/cd_errors.c
- source/backend/builtins/cd/cd_utils.c
- source/backend/builtins/pwd.c
- source/backend/redirection/io_file.c
- source/backend/redirection/stdio_bind.c
Standardize error message printing to always only use one function that prints the actual message.
- `print_error()` if more than just the program name should be in front of the error message.
- `perror()` if just the program name should be in front.
> [REFACTOR] Prevent mixed error messages by standardizing how errors are printed

- README.md
- Add line about sequential operator `;` (not supported).
- Add line about Local Variable Assignment (not supported).
- Specify Wildcard Expansion to be in the current directory.
- Change Brace Expansion from supported to not supported.
- Mention braces in Parameter Expansion.
- Change `ASSIGNMENT_WORD` from "support" to "recognize".
- Fix grammar and tense.
- Format raw markdown.
> [DOC] Update supported features table

- Makefile
> [BUILD] Add hint to `make help` when just running `make`

- .github/workflows/lines_of_code.yaml
- README.md
- It does not count empty and comment lines.
- It does count Markdown lines.
- It counts the following languages:
- C
- C/C++ Header
- make
- YAML
- Python
- Bourne Shell
- Bourne Again Shell
- yacc
- Markdown
- Dockerfile
> [DOC] Fix lines of code badge with GH Actions

- .github/workflows/lines_of_code.yaml
> [CI] Add job summary to the lines of code workflow

- .github/workflows/regression_test.yaml
- .github/workflows/test.yaml
This reduces a lot of duplicate code.
> [CI] Use a reusable workflow for regression test

- .github/workflows/regression_test.yaml
- .github/workflows/test.yaml
Bernhard and Istvan already ran out of GH Action minutes because one of the test cases caused an infinite loop.
Since the tests are so heavily parallelized, each of the runners ran into the timeout and cost minutes.
> [CI] Reduce timeouts in GH Actions

- .github/actions/setup/action.yaml
- .github/actions/summary_test_result/action.yaml
- .github/scripts/print_all_failed_test_cases.sh
- .github/scripts/print_changed_test_cases.sh
- .github/scripts/print_leak_test_cases.sh
- .github/workflows/delivery.yaml
- .github/workflows/regression_test.yaml
- .github/workflows/test.yaml
---
- setup action:
Making the inputs optional and checking if they are set before using them allows to set up less when not needed.
An example is the compilation test.
- summary action:
Using env was hard to follow and required comments in the action what was required for that action to work.
- delivery workflow:
Split up delivery workflow into 2 jobs.
Using jobs for controling the flow is better GitHub Actions practice than constant if checks.
> [CI] Use `inputs` for actions to enforce correct use

- Makefile
[![image](https://github.com/user-attachments/assets/1015c9c0-16b0-4822-983d-55e07ad86d43)](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html#:~:text=SCCS%20get%20program.-,LDFLAGS,-%C2%B6)
I also finally understand why the order of the linker flags matters!
**First the flags, then the source files which need the libraries, then the libraries.**
This is because the linker looks for the symbols missing in a given file only in the files coming after it.
The location of where to look for the libraries (`-L` / `LDFLAGS`) is a flag for the linker, so it should be in front.
And the actual libraries to include (`-l` / `LDLIBS`) need to be after the object files.
That's why it makes sense that `LDFLAGS` and `LDLIBS` are separate variables.
> [BUILD] Use make's linker flags for libraries

- .gitignore
- Makefile
- Also update .gitignore file for use with clangd + bear.
> [BUILD] Use conventional preprocessor variable name

- README.md
Before, checking `echo $?` after the command would always return 0 bc the last command run was `rm -f`.
Now, the command prints the exit code as well as exits with the exit code of minishell.
I did this after Vikas told me he found it confusing why the exit code was always 0 with this command.
> [DOCS] Improve valgrind command to display exit code

- Makefile
This makes the Makefile easier to reuse for other projects, also with other languages, like C++. 
Today I debugged my C++ Makefile, which is based on this one, for a long time bc I missed that it expected source files to end with `.c` and not `.cpp`.
> [BUILD] Add a `SRC_EXTENSION` variable to Makefile

- .github/actions/setup/action.yaml
GitHub updated the default image of `ubuntu-latest` to 24.04 from 22.04.
In that image clang-12 and libreadline-dev were missing.
> [CI] Fix clang-12 install issue with newest Ubuntu 24.04 image

- .github/workflows/test_image.yaml
- include/defines.h
- source/backend/executor/control_operator.c
- source/backend/executor/wait_process.c
- Fixes programs with exit code 130 causing a newline.
- Fixes minishell running in minishell printing too many newlines after SIGINT + exit.
- Fixes nested subshells printing too many newlines: `( ( (cat) ) )`
- Fixes `cat | ./segfault` behavior: `Segmentation fault` only gets printed at end of pipeline.
- This also fixes the exit code affecting `&&`/`|| `: `./return_130 || echo 123` did not print `123`.
- Resolves #257
---
- `(sleep 3 && ./segfault)` should not print `Segmentation fault` (which is super weird bc `(./segfault)` **does** print `Segmentation fault`!
- SIGQUIT behavior in subshells remains unsolved - #206
> [FIX] Fix newline after program with exit code 130

- Makefile
- **Properly display escape sequence printouts on all systems**
By default, Make uses `/bin/sh` and it does not interpret the escape sequences on all systems without the `-e` flag, but the `-e` flag is not supported on all systems with `sh`.
- **Remove unnecessary `--read-var-info=yes` valgrind flag**
It slows down valgrind's startup time significantly and produces unsupported DWARF warnings on campus environment.
Even if it would work, the information it produces is not really needed. Considering all this, it's understandable why it is under "Uncommon Options" in valgrind's manual.
- **Support multiple terminal emulators in `term` target**
> [BUILD] Makefile compatibility
